chronos/projetos/urls.py
from django.urls import path
from chronos.projetos import views


urlpatterns = [
    path('', views.ProjetosListView.as_view(), name="projeto-list"),
    path('criar', views.ProjetosCreateView.as_view(), name="projeto-add"),
    path('detalhe/<int:pk>', views.ProjetosDetailView.as_view(), name="projeto-detail"),
    path('editar/<int:pk>', views.ProjetosUpdateView.as_view(), name="projeto-update"),
    path('excluir/<int:pk>', views.ProjetosDeleteView.as_view(), name="projeto-delete"),
]

chronos/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('chronos.core.urls')),
    path('clientes/', include('chronos.clientes.urls')),
    path('projetos/', include('chronos.projetos.urls')),
    path('tarefas/', include('chronos.tarefas.urls')),
    path('reunioes/', include('chronos.reunioes.urls')),
    path('admin/', admin.site.urls),
]

chronos/projetos/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from chronos.clientes.models import Cliente


class Projeto(models.Model):

    class Meta:
        ordering = ["pago", "nome"]
        permissions = [
            ("can_view_payment_info", "Can view payment information"),
        ]

    class StatusProjeto(models.TextChoices):
        ORCADO = "ORC", _("Orçado")
        CONTRATADO = "CTD", _("Contratado")
        ANDAMENTO = "AND", _("Andamento")
        CONCLUIDA = "CON", _("Concluido")
        BLOQUEADO = "BLO", _("Bloqueado")

    class StatusPagamento(models.TextChoices):
        ABERTO = "ABE", _("Aberto")
        CONCLUIDO = "CON", _("Concluido")
        PARCELADO = "PAR", _("Parcelado")
        ATRAZADO = "ATR", _("Atrasado")
        PERDIDO = "PER", _("Perdido")

    nome = models.CharField(max_length=200)
    cliente = models.ForeignKey(
        Cliente, on_delete=models.CASCADE, related_name="projetos"
    )
    valor = models.DecimalField(max_digits=12, decimal_places=2, default=0, null=True)
    pago = models.BooleanField(default=False, null=True)
    pagamento = models.CharField(
        max_length=3,
        choices=StatusPagamento,
        default=StatusPagamento.ABERTO,
    )
    status = models.CharField(
        max_length=3,
        choices=StatusProjeto,
        default=StatusProjeto.ORCADO,
    )

    def __str__(self):
        return f"{self.nome} ({self.cliente.nome})"

    def get_absolute_url(self):
        return reverse("tarefa-projeto-list", kwargs={"projeto_id": self.pk})

chronos/projetos/forms.py
from django import forms
from chronos.projetos.models import Projeto


class ProjetoForm(forms.ModelForm):
    class Meta:
        model = Projeto
        fields = ["nome", "cliente", "valor", "pagamento", "status"]
        widgets = {
            'valor': forms.TextInput(attrs={
                'class': "maskmoney",
            }),
        }
    

chronos/projetos/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from loguru import logger
from django import forms
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    CreateView,
    UpdateView,
    DeleteView,
    DetailView,
)
from chronos.projetos.models import Projeto
from chronos.projetos.filters import ProjetoFilter
from chronos.projetos.forms import ProjetoForm


class ProjetosListView(LoginRequiredMixin, ListView):
    model = Projeto
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = ProjetoFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context


class ProjetosCreateView(LoginRequiredMixin, CreateView):
    model = Projeto
    form_class = ProjetoForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if "data" in kwargs.keys():
            querydict = kwargs["data"].copy()
            querydict["valor"] = float(
                querydict["valor"].replace(".", "").replace(",", ".")
            )
            kwargs["data"] = querydict
        return kwargs

    def get_form(self):
        form = super().get_form()
        if not self.request.user.has_perm("projetos.can_view_payment_info"):
            form.fields['valor'].widget = forms.widgets.HiddenInput()
            form.fields['pago'].widget = forms.widgets.HiddenInput()
        return form


class ProjetosUpdateView(LoginRequiredMixin, UpdateView):
    model = Projeto
    form_class = ProjetoForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if "data" in kwargs.keys():
            querydict = kwargs["data"].copy()
            querydict["valor"] = float(
                querydict["valor"].replace(".", "").replace(",", ".")
            )
            kwargs["data"] = querydict
        if "instance" in kwargs.keys():
            kwargs["instance"].valor = str(kwargs["instance"].valor).replace(".", ",")
        return kwargs

    def get_success_url(self):
        context = self.get_context_data()
        projeto = context["projeto"].pk
        url = self.request.GET.get("redirect", "projeto-list")
        if url == "tarefa-projeto-list":
            return reverse(url, kwargs={"projeto_id": projeto})
        return reverse(url)

    def get_form(self):
        form = super().get_form()
        if not self.request.user.has_perm("projetos.can_view_payment_info"):
            form.fields['valor'].widget = forms.widgets.HiddenInput()
            form.fields['pago'].widget = forms.widgets.HiddenInput()
        return form


class ProjetosDeleteView(LoginRequiredMixin, DeleteView):
    model = Projeto
    success_url = reverse_lazy("projeto-list")


class ProjetosDetailView(LoginRequiredMixin, DetailView):
    model = Projeto

chronos/projetos/templates/projetos/projeto_confirm_delete.html
{% extends 'content.html'%}

{% block 'content-title'%}
Lista de Projetos
{% endblock%}

{% block 'content'%}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-header">
                        <h3 class="card-title">Excluir Projeto</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        Deseja mesmo excluir todos os dados do projeto: {{object}} ??
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <a href="{% url 'projeto-list' %}" class="btn btn-info">Não</a>
                        <button type="submit" class="btn btn-info">Sim</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
{% endblock %}

chronos/projetos/templates/projetos/projeto_detail.html
{% extends 'content.html'%}

{% block 'content-title'%}
Lista de Projetos
{% endblock%}

{% block 'content'%}
  <div class="row">
    <div class="col-lg-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title"></h3>
          <div class="card-tools">
            <div class="btn-group">
                <a href="{% url 'projeto-list' %}" class="btn btn-info">Listagem</a>
                <a href="{% url 'projeto-update' object.pk %}" class="btn btn-info">Editar</a>
                <a href="{% url 'projeto-delete' object.pk %}" class="btn btn-info">Excluir</a>
            </div>
          </div>
        </div>
        <div class="card-body">
            {{object}}
        </div>
      </div>
    </div>
  </div>
{% endblock %}

chronos/projetos/templates/projetos/projeto_form.html
{% extends 'content.html'%}
{% load crispy_forms_tags %}

{% block 'content-title'%}
{% if object.pk %}
Editando Projeto <small>#{{object.pk}}</small>
{% else %}
Novo Projeto
{% endif %}
{% endblock%}

{% block 'content'%}
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <form method="post">
                    {% csrf_token %}
                    <div class="card-header">
                        <h3 class="card-title">Projeto</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        {{form|crispy}}
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-info">Salvar</a>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
{% endblock %}

chronos/projetos/templates/projetos/projeto_list.html
{% extends 'content.html'%}
{% load crispy_forms_tags static widget_tweaks %}


{% block 'content-title'%}
Lista de Projetos
{% endblock%}

{% block 'content'%}
<div class="container-fluid w-100 p-2">
    <div class="card card-default collapsed-card w-100">
    <div class="card-header">
    <h3 class="card-title">Filtros</h3>

    <div class="card-tools">
        <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-plus"></i>
        </button>
    </div>
    <!-- /.card-tools -->
    </div>
    <!-- /.card-header -->
    <div class="card-body">
    <form method="get">
        {{ filter.form | crispy }}
        <button type="submit" class="btn btn-default">Filtrar</button>
    </form>
    </div>
    <!-- /.card-body -->
    </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"></h3>
        <div class="card-tools">
          <a href="{% url 'projeto-add' %}" class="btn btn-block btn-info">Adicionar Projeto</a>
        </div>
      </div>
      <!-- /.card-header -->
      <div class="card-body p-0">
        <table class="table table-striped">
          <thead>
            <tr>
              {% if 'projeto.can_view_payment_info' in perms %}
              <th>Pagamento</th>
              {% endif %}
              <th>Cliente</th>
              <th>Projeto</th>
              <th>Status</th>
              <th>Tarefas</th>
              <th class="text-right">Ações</th>
            </tr>
          </thead>
          <tbody>
            {% for object in object_list %}
            <tr>
              {% if 'projeto.can_view_payment_info' in perms %}
              <td>
                {{ object.get_pagamento_display }}
              </td>
              {% endif %}
              <td>
                <a href="{{object.cliente.get_absolute_url}}">
                  {{object.cliente}}
                </a>
              </td>
              <td>
                <a href="{% url 'tarefa-projeto-list' object.pk %}" class="link">
                  {{object.nome}}
                </a>
              </td>
              <td>
                {{object.get_status_display}}
              </td>
              <td>
                {{object.tarefas.count}}
              </td>
              <td class="text-right">
                <div class="btn-group">
                  <a href="{% url 'projeto-update' object.pk %}" class="btn btn-success">
                    <i class="fas fa-edit"></i>
                  </a>
                  <a href="{% url 'projeto-delete' object.pk %}" class="btn btn-danger">
                    <i class="fas fa-trash"></i>
                  </a>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <!-- /.card-body -->
      <div class="card-footer">
        {% if is_paginated %}
        <ul class="pagination pagination-sm float-right">
          {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Anterior</a></li>
          {% endif %}
          <li class="page-item">
            <a class="page-link" href="#">
              Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Proxima</a></li>
          {% endif %}
        </ul>
        {% endif %}
      </div>
    </div>
    <!-- /.card -->
  </div>
</div>
{% endblock %}